### PR TITLE
Release v0.3.0

### PR DESCRIPTION
**Pull request by dmikurube**
@muga Upgrading to 0.3.0. (Major version up because of the incompatibility.)

### CODE REVIEW

**Review by muga — APPROVED** [review]
LGTM 👍

**Comment by dmikurube** [comment]
Thanks. To be releasing the new version.

**Comment by dmikurube** [comment]
@muga Released: https://rubygems.org/gems/embulk-executor-mapreduce/versions/0.3.0

**Comment by muga** [comment]
Thank you!

**Pull request merged**
