### PR TITLE
Build embulk-executor-mapreduce_2_6 and embulk-executor-mapreduce_2_7

### PR DESCRIPTION
**Pull request by dmikurube**
@muga Jfyi: trying to build 2_6 and 2_7 with the same source tree. Let me share this although it has a remaining problem.

### CODE REVIEW

**Comment by dmikurube** [comment]
MEMO: The remaining problem is in `TestMapReduceExecutor`. It uses Embulk configurations under `src/test/resources/configs`. The configs expect Embulk running at `embulk-executor-mapreduce/`.

It was good before this PR as the "working directory" is actually (sub-)project's top directory in Gradle. After this PR, Embulk runs at `embulk-executor-mapreduce_2_6/` or `embulk-executor-mapreduce_2_7/`.

One solution may be replacing `src/test/resources` to `build/resources/test` in the config files, but it may be still a bit ad-hoc...

**Comment by dmikurube** [comment]
Ah, just ^ does not solve. The configs (e.g. [`embulk_mapred_config.yml`](https://github.com/embulk/embulk-executor-mapreduce/blob/1b18884aaa43062903d1714155fe435b60e6506f/embulk-executor-mapreduce/src/test/resources/config/embulk_mapred_config.yml)) have the fixed plugin name `mapreduce` there. We need to make them variable like `mapreduce_2_6` and `mapreduce_2_7`.

**Comment by muga** [comment]
Thank you for investigating. Yea, we need to make them variable. Or we need to merge `exec:` config for each executor type like
```
embulk-executor-mapreduce/src/test/resources/config/embulk_mapred_config.yml # existing file
embulk-executor-mapreduce_2_6/src/test/resources/config/embulk_mapred_exec_config.yml # executor config should be merged?
embulk-executor-mapreduce_2_7/src/test/resources/config/embulk_mapred_exec_config.yml # should be merged?
```

**Comment by muga** [comment]
@dmikurube I fixed tests to change base path of test data resources and confirmed that unit tests for 2_6 and 2_7 work on local. How about this?

**Comment by dmikurube** [comment]
@muga Thanks for fix it to work. LGTM! (But, since I was the author of this PR, I couldn't "approve" on GitHub... ;) )

**Comment by muga** [comment]
@dmikurube ah, thank you for reviewing. it looks good to me too.

**Review by muga — APPROVED** [review]

**Comment by muga** [comment]
Merging-

**Pull request merged**
