### PR TITLE
MapReduceExecutor throws ConfigException when no input files

### PR DESCRIPTION
**Pull request by muga**

### CODE REVIEW

**Comment by frsyuki** [comment]
If inputTaskCount is 0, outputTaskCount should be 0, correct? So, I think this is correct fix:

``` java
if (inputTaskCount > 0) {
    reduceTaskCount = task.getReducers().or(inputTaskCount);
    if (reduceTaskCount <= 0) {
        throw new ConfigException("Reducers must be larger than 1 if partition: is set");
    }
    outputTaskCount = reduceTaskCount;
} else {
    reduceTaskCount = 0;
    outputTaskCount = 0;
}
```

**Comment by frsyuki** [comment]
well, no. If input task count is 0, we can disable partitioning.
This line can add `&& inputTaskCount > 0` and `// here can disable partitioning and force set reduceTaskCount and outputTaskCount to 0 if inputTaskCount is 0`` comment: https://github.com/embulk/embulk-executor-mapreduce/blob/handle_no_input_files/embulk-executor-mapreduce/src/main/java/org/embulk/executor/mapreduce/MapReduceExecutor.java#L81

**Comment by muga** [comment]
> If input task count is 0, we can disable partitioning.

that's better. fixed c9cfe6be1134a5916f0ef61aa50b5524058c0fc3

**Comment by frsyuki** [comment]
:+1:

**Pull request merged**
