### PR TITLE
Add embulk-executor-mapreduce_2_7.

### PR DESCRIPTION
**Pull request by dmikurube**
@muga After #39, this tries to add embulk-executor-mapreduce_2_7 depending on `org.apache.hadoop:hadoop-client:2.7.3`.

Because the source code are totally the same, we may have another better approach only within `build.gradle`, though.

### CODE REVIEW

**Comment by muga** [comment]
@dmikurube thank you for moving forward hadoop 2.7 upgrading for MapReduceExecutor. 

> Because the source code are totally the same, we may have another better approach only within build.gradle, though.

Totally agree. Did you have any difficulties to take this approach?

**Comment by dmikurube** [comment]
No specially. This PR's just testing.

**Comment by muga** [comment]
Ok, please let me know if this PR is ready to review. I think that this PR is still testing now. Please correct me.

**Comment by muga** [comment]
@dmikurube I close this ticket because #42 was merged instead of this. Please let me know and feel free to open it if needed.

**Comment by dmikurube** [comment]
Thanks!

**Pull request closed without merging**
