### PR TITLE
Fix for Embulk 0.8.24 on 'new PluginType("local")'.

### PR DESCRIPTION
**Pull request by dmikurube**
@muga Hmm, this is an unexpected breakage caused by: https://github.com/embulk/embulk/pull/666

This PR is a quick fix, but we may want another better fix (maybe on Embulk's side). What do you think?

### CODE REVIEW

**Review by muga — APPROVED** [review]
LGTM. Thank you for fixing.

**Comment by dmikurube** [comment]
@muga Thanks. Merging this.

We'll be releasing a new version of the plugin?

**Comment by muga** [comment]
@dmikurube It's better to release this before #40. I will ask @frsyuki to give us a permission to do that.

**Comment by dmikurube** [comment]
Agreed. It's to be released before #40.

**Comment by muga** [comment]
Can you release new version? The permission was provided to us.

**Comment by dmikurube** [comment]
Ah, sorry, I was not aware of the comment of yours. To be releasing at #41.

**Pull request merged**
